plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'net.minecraftforge.gradle' version '6.0.+'
	id 'maven-publish'
}

repositories {
	maven {
		name = 'spigotmc'
		url = 'https://hub.spigotmc.org/nexus/repository/public'
	}
	mavenCentral()
}

// Project settings
java {
	toolchain.languageVersion = JavaLanguageVersion.of(8)
	sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

minecraft {
	mappings channel: 'stable', version: '39-1.12'
	accessTransformer = file('src/main/resources/META-INF/bukkitevents_at.cfg')
}

dependencies {
	minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'
	api 'org.bukkit:bukkit:1.12.2-R0.1-SNAPSHOT'
}

processResources {
	// redo task if any of these properties change
	inputs.property 'version', project.version
	duplicatesStrategy = DuplicatesStrategy.INCLUDE

	// Replace properties in all files
	from(sourceSets.main.resources.srcDirs) {
		include 'mcmod.info'
		expand 'version': project.version
	}
}

jar {
	manifest {
		attributes 'FMLCorePluginContainsFMLMod': 'true'
		attributes 'FMLCorePlugin': 'me.theandrey.bukkit.internal.asm.LoadingPlugin'
		attributes 'FMLAT': 'bukkitevents_at.cfg'
	}
}

tasks.register('devJar', Jar) {
	archiveClassifier.set('dev')
	manifest = jar.manifest
	from sourceSets.main.output
}

tasks.register('sourcesJar', Jar) {
	archiveClassifier.set('sources')
	from sourceSets.main.allSource
}

artifacts {
	archives tasks.devJar
	archives tasks.sourcesJar
}

tasks.withType(GenerateModuleMetadata).configureEach {
	enabled = false
}

publishing {
	repositories {
		maven {
			name = 'redserver'
			url = findProperty('ru.redserver.repository.publish_url')
			credentials() {
				username findProperty('ru.redserver.repository.username')
				password findProperty('ru.redserver.repository.password')
			}
		}
	}

	publications {
		register('mavenJava', MavenPublication) {
			version = project.pom_version

			from components.java
			artifact tasks.named('devJar')
			artifact tasks.named('sourcesJar')

			/* Remove ForgeGradle deps */
			pom.withXml {
				Node pomNode = asNode()
				pomNode.dependencies.'*'.findAll() {
					it.groupId.text() == 'net.minecraftforge'
				}.each() {
					it.parent().remove(it)
				}
			}
		}
	}
}
